# Generated by Django 4.1.7 on 2023-03-31 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
